name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libopenmpi-dev openmpi-bin cmake
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.22"
          enable-cache: true
      - name: Sync dependencies
        run: uv sync --group dev
      - name: Run tests
        run: uv run pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libopenmpi-dev openmpi-bin cmake
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.22"
          enable-cache: true
      - name: Sync dependencies
        run: uv sync
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
